# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Tython
email: support@tython.co
description: >- # this means to ignore newlines until "baseurl:"
  Tython provides consulting services to Salesforce partners, customers, and ISVs with a focus on lightning components, Apex development, and backend integrations.
baseurl: "" # the subpath of your site, e.g. /blog
url: "tython.co" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: tythonco
github_username:  tythonco
repo_name: "tython-website"
examples_url: "https://github.com/tythonco/tython-website/tree/master/examples"
permalink: /:categories/:year/:month/:day/:title:output_ext

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-titles-from-headings
  - jemoji
titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true 

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - examples/
  - Gemfile
  - Gemfile.lock
  - .gitignore
  - node_modules
  - out/
  - package-lock.json
  - package.json
  - README.md
  - .sfdx/
  - TI/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
