name: AutoPublish

on:
  workflow_dispatch:
  schedule:
    - cron: '10 03 * * 2'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest    
    environment: github-pages
    steps:
    - uses: actions/checkout@v2
    - name: Jekyll Publish Drafts
      uses: soywiz/github-action-jekyll-publish-drafts@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        jekyll_path: ./