name: AutoPublish

on:
  push:
    branches:
      - main
      - master
  schedule:
    - cron: '0 14 * * 1-5'
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest    
    environment: github-pages
    steps:
    - uses: actions/checkout@v2
    - name: Jekyll Publish Drafts
      uses: tythonco/github-action-jekyll-publish-drafts@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        jekyll_path: ./